name: supernova_translator
description: Supernova translator test project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^5.0.0  
  mobx: ^2.0.1  
  flutter_mobx: ^2.0.0  
  shared_preferences: ^2.0.5
  dio: ^4.0.0
  connectivity_plus: ^1.0.0
  another_flushbar: ^1.10.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  build_runner: ^1.12.2
  mobx_codegen: ^2.0.1+2

  
flutter:
  uses-material-design: true
